spring:
  application:
    name: webhooker

  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: password1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect